name: schulcloud
description: A Flutter–based mobile app for the HPI Schul–Cloud.
version: 1.0.0+1
authors:
  - Clemens Tiedt
  - Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/schul-cloud/schulcloud-flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_villains: ^1.2.0
  http: ^0.12.0
  path_provider: ^1.1.0
  provider: ^3.0.0
  repository: ^1.0.0
  repository_hive: ^1.0.1
  repository_shared_preferences: ^1.0.1
  rxdart: ^0.22.0
  transparent_image: ^1.0.0
  webview_flutter: ^0.3.10+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  hive_generator:
    git:
      url: git://github.com/marcelgarus/hive.git
      path: hive_generator
  json_serializable: ^3.0.0
  test: any

flutter:
  uses-material-design: true

  fonts:
  - family: PT Sans
    fonts:
    - asset: assets/PT_Sans-Web-Regular.ttf
  - family: PT Sans Narrow
    fonts:
    - asset: assets/PT_Sans-Narrow-Web-Regular.ttf
      weight: 300
    - asset: assets/PT_Sans-Narrow-Web-Bold.ttf
      weight: 700
