name: schulcloud
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_villains: ^1.2.0
  http: any
  json_annotation: ^2.0.0
  provider: ^2.0.1
  rxdart: any
  shared_preferences: any
  transparent_image: any

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: any
  test: any

flutter:
  uses-material-design: true

  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/PT_Sans-Web-Regular.ttf
    - family: PT Sans Narrow
      fonts:
        - asset: assets/PT_Sans-Narrow-Web-Regular.ttf
          weight: 300
        - asset: assets/PT_Sans-Narrow-Web-Bold.ttf
          weight: 700
