name: schulcloud
description: A Flutter–based mobile app for the HPI Schul–Cloud.
version: 1.0.0+1
authors:
  - Marcel Garus <marcel.garus@gmail.com>
  - Andrea Nathansen
  - Clemens Tiedt
homepage: https://github.com/schul-cloud/schulcloud-flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer: ^0.38.5
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.5.8
  flutter_cached: ^3.0.1
  # The current version of flutter_downloader, 1.2.1, causes the build to fail. Until this is fixed, we rely on an older version.
  flutter_downloader: 1.1.9
  flutter_html: ^0.10.4
  flutter_svg: ^0.14.2
  flutter_villains: ^1.2.0
  hive: ^1.1.1
  http: ^0.12.0
  intl: ^0.16.0
  list_diff: ^1.1.3
  package_info: ^0.4.0+3
  path_provider: ^1.1.0
  permission_handler: ^3.3.0
  provider: ^3.0.0
  rxdart: ^0.22.3
  streaming_shared_preferences: ^1.0.1
  transparent_image: ^1.0.0
  url_launcher: ^5.1.2
  webview_flutter: ^0.3.10+4

dev_dependencies:
  build_resolvers: ^1.1.1
  build_runner: ^1.0.0
  hive_generator: ^0.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/empty_states/default.svg
    - assets/empty_states/broken_pen.svg
    - assets/empty_states/files.flr
    - assets/logo/logo_with_text.svg
    - assets/file_thumbnails/

  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/fonts/pt_sans_regular.ttf
          weight: 300
        - asset: assets/fonts/pt_sans_bold.ttf
          weight: 700
    - family: PT Sans Narrow
      fonts:
        - asset: assets/fonts/pt_sans_narrow_regular.ttf
          weight: 300
        - asset: assets/fonts/pt_sans_narrow_bold.ttf
          weight: 700
