name: schulcloud
description: A Flutter–based mobile app for the HPI Schul–Cloud.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  repositories:
    path: ../repositories

  cupertino_icons: ^0.1.2
  flutter_villains: ^1.2.0
  http: ^0.12.0
  path_provider: ^1.1.0
  provider: ^3.0.0
  rxdart: ^0.22.0
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  entity_generator:
    path: ../entity_generator

  build_runner: ^1.0.0
  hive_generator: any
  json_serializable: ^3.0.0
  test: any

flutter:
  uses-material-design: true

  fonts:
  - family: PT Sans
    fonts:
    - asset: assets/PT_Sans-Web-Regular.ttf
  - family: PT Sans Narrow
    fonts:
    - asset: assets/PT_Sans-Narrow-Web-Regular.ttf
      weight: 300
    - asset: assets/PT_Sans-Narrow-Web-Bold.ttf
      weight: 700
