name: schulcloud
description: A Flutter–based mobile app for the HPI Schul–Cloud.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # The current version of flutter_downloader, 1.2.1, causes the build to fail. Until this is fixed, we rely on an older version.
  flutter_downloader: 1.1.9
  flutter_html: ^0.10.4
  flutter_villains: ^1.2.0
  http: ^0.12.0
  json_annotation: ^2.0.0
  path_provider: ^1.1.0
  permission_handler: ^3.2.2
  provider: ^3.0.0
  rxdart: ^0.22.0
  shared_preferences: ^0.5.3
  sqflite: ^1.1.6
  transparent_image: ^1.0.0
  webview_flutter: ^0.3.10+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  test: ^1.6.0

flutter:
  uses-material-design: true

  fonts:
  - family: PT Sans
    fonts:
    - asset: assets/PT_Sans-Web-Regular.ttf
  - family: PT Sans Narrow
    fonts:
    - asset: assets/PT_Sans-Narrow-Web-Regular.ttf
      weight: 300
    - asset: assets/PT_Sans-Narrow-Web-Bold.ttf
      weight: 700
