on: [push, pull_requests]
name: build and test app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies from pub
        uses: steebchen/flutter@v1.0.0
        with:
          args: pub get

      - name: Auto-generate code using the build_runner
        uses: steebchen/flutter@v1.0.0
        with:
          args: pub run build_runner build

      - name: Analyze and lint the code
        uses: steebchen/flutter@v1.0.0
        with:
          args: analyze

      - name: Build apk
        uses: steebchen/flutter@v1.0.0
        with:
          args: build apk --release
