name: Build & Lint

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  install:
    name: Install Flutter & dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Run code generator(s)
        run: |
          flutter pub run intl_utils:generate
          flutter pub run build_runner build

      - name: Remove obsolete files
        run: |
          rm -rf ./.dart_tool/pub/bin/build_runner
      - name: Persist current state
        uses: actions/upload-artifact@v1
        with:
          name: source
          path: .

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Checkout source
        uses: actions/download-artifact@v1
        with:
          name: source
          path: .

      - name: Run linter
        run: flutter analyze > flutter_analyze_report.txt
        continue-on-error: true

      - name: Install ruby
        uses: actions/setup-ruby@v1
        if: github.event_name == 'pull_request'
        with:
          ruby-version: "2.6"
      - name: Install ruby gems
        run: |
          gem install bundler
          bundle install --without documentation
        if: github.event_name == 'pull_request'
      - name: Run danger on generated report
        uses: MeilCli/danger-action@v1
        if: github.event_name == 'pull_request'
        with:
          danger_file: Dangerfile
          danger_id: "danger-pr"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["sc", "brb", "n21", "open", "thr"]
      fail-fast: false
    steps:
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Checkout source
        uses: actions/download-artifact@v1
        with:
          name: source
          path: .

      # The default (sc) flavor doesn't have a special main.dart-suffix
      - if: matrix.flavor == 'sc'
        run: flutter build apk --flavor=sc
        env:
          RELEASE_USE_DEBUG_KEY: true
      - if: matrix.flavor != 'sc'
        run: flutter build apk --target=lib/main_${{ matrix.flavor }}.dart --flavor=${{ matrix.flavor }}
        env:
          RELEASE_USE_DEBUG_KEY: true

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v1
        with:
          name: apk-${{ matrix.flavor }}
          path: build/app/outputs/apk/${{ matrix.flavor }}/release

  # TODO(JonasWanke): enable screenshots when this issue is fixed: https://github.com/flutter/flutter/issues/36244
  # generate-screenshots:
  #   name: Generate screenshots
  #   needs: install
  #   # We have to use macOS for hardware acceleration on Android emulators
  #   runs-on: macos-10.15
  #   strategy:
  #     matrix:
  #       flavor: ["sc"]
  #     fail-fast: false
  #   steps:
  #     - name: Install Java 12
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - name: Install Flutter (stable)
  #       uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - name: Checkout source
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: source
  #         path: .
  #     - name: Install Java 10
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 10
  #     - name: Create virtual device
  #       run: |
  #         ~/Library/Android/sdk/tools/bin/sdkmanager "system-images;android-28;default;x86"
  #         echo no | ~/Library/Android/sdk/tools/bin/avdmanager --verbose create avd --force --name "Pixel_XL" --package "system-images;android-28;default;x86" --device "pixel_xl"
  #       env:
  #         JDK_JAVA_OPTIONS: "--add-modules java.xml.bind"
  #     - name: Install screenshots package
  #       run: |
  #         brew update && brew install imagemagick
  #         flutter pub global activate screenshots
  #     - name: Take screenshots
  #       run: flutter pub global run screenshots:main -v -f sc
  #     - name: Upload screenshots as artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: screenshots-${{ matrix.flavor }}
  #         path: android/fastlane/metadata/android
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: tmp-screenshots
  #         path: /tmp/screenshots

  deploy-canary:
    name: Deploy canary
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["sc"]
      fail-fast: false
    steps:
      - name: Install Java 12
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Checkout source
        uses: actions/download-artifact@v1
        with:
          name: source
          path: .

      - name: Store Google Play credentials in a file
        run: echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ./android/fastlane/googlePlay-serviceAccount.json
      - name: Store Google Play upload key in a file
        run: echo "${{ secrets.GOOGLE_PLAY_UPLOAD_KEY }}" | base64 --decode > ./android/upload.keystore.jks
      - name: Build AAB with updated version
        uses: JonasWanke/unicorn@fix/google-play-deployment
        with:
          repo-token: "${{ secrets.UNICORN_TOKEN }}"
        env:
          UPLOAD_KEY_STORE_PASSWORD: ${{ secrets.GOOGLE_PLAY_UPLOAD_KEY_STORE_PASSWORD }}
          UPLOAD_KEY_KEY_PASSWORD: ${{ secrets.GOOGLE_PLAY_UPLOAD_KEY_KEY_PASSWORD }}
      - name: Deploy to Google Play (internal track)
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: canary
          subdirectory: android
